version: '3'
services:
  easy-time-pg:
    image: bitnami/postgresql
    ports:
      - 5455:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=easytime